### ISSUE TITLE
Automatically include $$ in input text box (QOL)

### ISSUE THREAD

**Issue by ngoonee** [textext/textext#115]
**Is your feature request related to a problem? Please describe.**
I've forgotten to do the above more times than I care to recall.

**Describe the solution you'd like**
When creating a new Tex Text, instead of starting with nothing in the input text box, start with $$. Even better if the cursor is automatically between both the $.

**Additional context**
The alternative is to automatically include $$ around the expression if it's not provided at all (assuming there's no reason to use Latex in inkscape if not for the mathematics bit), but that's probably too auto-magical.

My assumption here, based on my own use-case, is that Latex is primarily used to input various mathematical formulae, and easing this would be the goal of this plugin.

**Comment by sizmailov** [comment]
Thanks for suggestion! I believe most of TexText users use it for math only as well. 

I think we can introduce a global config option to set initial text of TexText window for new objects.

Three choices will be available: 
- no text, the default one, current behavior 
- inline math ($<cursor>$)
- display math ($$<cursor>$$)

Automatic inclusion of $ is not a good option. How would you know what `x` input stands for? Is it plain text or `$x$` was meant? TexText is not able to read user's mind (yet). 

@ngoonee Do you want to implement it?

**Comment by ngoonee** [comment]
A fourth option (automatic inclusion of $$ no matter what) makes sense in my mind, because it would never be the default and the user would have to select it.

Never looked at touching the code before, but since it's python, seems possible. Any 'reference' pull request which accomplishes something similar (in particular UI wise for the global config option)?

**Comment by sizmailov** [comment]
Here are related PRs: #79, #89. Feel free to create work-in-progress PR. I'll make review to keep it in line with plugin. 

Well. You may make a forth option. Test it for a week or so and tell how convenient it is.

**Comment by sizmailov** [comment]
I have implemented the requested feature, see PR. 

@ngoonee I didn't add "automatic inclusion of `$$`" options since this use case is virtually covered by other options. Automatic inclusion also complicates temporary use of plain text. To do that you need to 1) select "empty" option, 2) close window,  3) run TexText again, 4) switch back to automatic mode. If you have explicit `$$` all you need is delete `$$`.

Cursor is placed in between of `$$` so you can type you formula right away. 

@jcwinkler How do you feel about this feature?
