### ISSUE TITLE
Adding the package to one of the Windows package managers

### ISSUE THREAD

**Issue by Foadsf** [textext/textext#117]
**Problem**
This package has a lot of dependencies which novice user like me has a hard time to install. 

**Solution**
It would be great if it could be added to the common windows package managers like [Chocolatey ](https://chocolatey.org/) or [Scoop ](https://scoop.sh/).

**Comment by sizmailov** [comment]
Thanks for the report! I agree, it would be nice to install TexText via 

```bash
choco install inkscape-plugin-textext
```

instead of (hypotetic) ten-liner:

```bash

# install dependencies
choco install inkscape 
choco install pdf2svg 
choco install miktex
choco install pygtk-2 # actually is not currently available 

# install TexText
wget https://github.com/textext/textext/archive/master.zip
unzip master.zip
cd textext
python setup.py
```

As you pointed out TexText has a number of dependencies. 

To make a TexText package we need all 3rd packages available. Unfortunately 
some of dependencies are missing in Chocolatey. 
List of dependencies on Chocholatey
 - :heavy_check_mark: inkscape  (https://chocolatey.org/packages/InkScape)
 - :x: pygtk (https://chocolatey.org/packages?q=pygtk)
 - :heavy_check_mark: miktex (https://chocolatey.org/packages/miktex)
 - :question: pdf2svg https://chocolatey.org/packages/pdf2svg
 - :x: pstoedit (https://chocolatey.org/packages?q=pstoedit)
 - :x: ghostscript (https://chocolatey.org/packages?q=ghostscript)

Scoop don't have inkscape, pstoedit, pdf2svg, pygtk. https://github.com/lukesampson/scoop/tree/master/bucket

I don't think it's reasonable to make a package until minimal set of dependencies will appear. At the same time once you have all dependencies available installation boils down to above ten-liner script... just as on linux

It sounds reasonable to file issues for all dependencies projects )

**Comment by Foadsf** [comment]
Dear @sizmailov I asked [this question](https://gitlab.gnome.org/GNOME/pygobject/issues/311#note_460885) on pygtk repo and this is their response:

> PyGTK is dead and superseded by PyGObject

and 

> Anyone should port any code that still uses PyGTK to PyGObject.

**Comment by leberwurstsaft** [comment]
Uh oh.

**Comment by sizmailov** [comment]
Actually the situation is quite different from the time when I wrote previous comment. 

We are going to port TexText to GTK3, so we plan to drop pygtk. This work is almost done, basically we need to double check the port (https://github.com/textext/textext/tree/feature/port_to_gtk3)

In inkscape-1.0 compatible release we are going to drop all `pdf->svg` 3rd party converters as well (pdf2svg, pstoedit and ghostscript). Inkscape will be able to do it on it's own. 

Once it's done we will have just three dependencies: Inkscape1.0+, *tex, GTK3. 

GTK3 is part of inkscape1.0 installation, but unfortunately python bindings are NOT guaranteed to be installed as well.

**Comment by jcwinkler** [comment]
> PyGTK is dead and superseded by PyGObject

Yes, indeed we move to GTK3. So this is not a problem. @sizmailov already implemented this. What has to be done is to provide the binaries in the Windows installer. I am working on this.

**Comment by jcwinkler** [comment]
See https://github.com/textext/textext/projects/1
