### ISSUE TITLE
Version numbering next release

### ISSUE THREAD

**Issue by jcwinkler** [textext/textext#155]
What do you think? Should the next release of TexText, which will be only compatible with Inkscape 1.0, get version number 1.0?

Personally I think this is OK. We have a rich set of features which are tested. Of course, there are always additional things which are nice to have.

1.0 would align prettily to Inkscape 1.0

If not, which number do you suggest? 0.9?

**Comment by sizmailov** [comment]
TexText is separate project and I don't see reasons to break rules of semantic versioning. Documents created with older versions will be compatible with new ones and vice versa. 

We already have 0.11, so next is 0.12. :)

**Comment by sizmailov** [comment]
Well. May be you are right and we need to change version to 1.0 since it will be incompatible with older inkscape versions. 

No one depends on TexText package as a library, so it perfectly fine to break machine rules. 
For people it would be natural to have 1.0 inkscape + 1.0 TexText or 0.x inkscape and 0.x TexText. 

I should have a thought before writing previous comment :)

**Comment by jcwinkler** [comment]
I really think it is reasonable to change to 1.0 according to semantic version rules (https://semver.org/):

- Incompatible with previous version of Inkscape (we do not offer an API but we use a different one in this release)
- We are really in a productive use now -> leave 0.x cycle

**Comment by sizmailov** [comment]
Ok, lets do it
