### ISSUE TITLE
TexText setup.bat failed to find Python

### ISSUE THREAD

**Issue by Akusho** [textext/textext#163]
Hello,
I installed everything as described in the "Install dependencies" section. When I run the setup.bat it tells me
"Trying to find Inkscape...
Trying registry root HKLM...
Trying registry root HKCU...
Inkscape found as REG_SZ    C:\Program Files\Inkscape\inkscape.exe

Trying to detect Python interpreter in Inkscape installation directory...
Trying to detect Python interpreter in python directory of Inkscape installation...
No Python interpreter found within your Inkscape installation.
You have to install Inkscape with the Python option enabled
in the Inkscape installer."

I installed Inkscape 0.94.4 64bit with python enabled (default installation), installed the PyGTK-2.24 as well, went to preferences and added the line to use Python 2.7, but nothing helps - I still get the same error.
What could be the issue?

EDIT: Installed Tex Text with the installer and nothing else. I can open the window and can type text and it will convert to svg text, however any special characters like greek letters - \alpha etc are not working, showing error.
Tried reinstalling everything both in 64 bit again and in 32bit (aside from MikTex) - nope, still nothing.
Tried copying over the Tex Text folder from AppData to share\extensions - doesn't help.

**Comment by jcwinkler** [comment]
To get things a littlebit ordered I have the following questions:

1. You were able to install TexText using the Installer TexText-Windows-0.11.0.exe, right?
2. You are able to compile LaTeX code, e.g. ``Hello world!``
3. If you try to compile ``$\alpha$`` you get an error? Which one?

**Comment by Akusho** [comment]
I tried installing Inkscape on a different PC and it not through the .msi
but through .exe and although the setup.bat still doesn't work, tells me
that it can't find setup.py, by installing tex text by using the .msi
package without checks it seems to work.

**Comment by jcwinkler** [comment]
Please carefully read my questions and give precise answers to them. Your comment is not an answer to any of my questions. Otherwise I cannot help.

**Comment by jcwinkler** [comment]
And, I guess you mean ``setup_win.bat``?

**Comment by SShafiP** [comment]
Hello, does TexText 1.3.0 (as updated on 2020-11-27) work with Inkscape 1.0.1 (released on 2020-09-07)?

I am getting a similar error while installing TexText using the recommended script setup. setup_win.bat fails to detect python.exe. It searches for python.exe in the Inkscape installation folder. However, python.exe is located in the Inkscape installation folder\bin folder (for example, if Inkscape is installed in C:\MyApps\Inkscape, then python.exe is located in C:\MyApps\Inkscape\bin).

Is there any easy fix to this?

**Comment by jcwinkler** [comment]
Hi! Thank you for the report. At first, could you please paste the output of the installation script?

For a quick installation, you have the following possibilities:

1. Just copy the entire `textext` folder you got while extracting the zip installation package into `C:\Users\[Your User Name]\AppData\Roaming\inkscape\extensions`. Launch Inkscape and see of the extensions appears under `Extensions\Text`.

2. Use the installer exe. It just does the copying of the files, no changes to the registry are performed.

>It searches for python.exe in the Inkscape installation folder. However, python.exe is located in the Inkscape installation folder\bin folder (for example, if Inkscape is installed in C:\MyApps\Inkscape, then python.exe is located in C:\MyApps\Inkscape\bin).

The script searches in the bin directory directory, as you mentioned, `%INKSCAPE_DIR%` is set to `C:\MyApps\Inkscape\bin`. Only idea I have at the moment is that the script detects a wrong Inkscape installation directory, e.g. from a corrupted registry value, as most likely in the OP.

**Comment by SShafiP** [comment]
Hello, and thank you very much for your prompt response. I have managed to work around this problem by using the installer (.exe file). Using the installer does not create any problems (at least, not in my knowledge).

Now, for the script, I did NOT copy the entire `textext` folder (obtained after extracting the zip installation package) into `C:\Users\[Your User Name]\AppData\Roaming\inkscape\extensions`. I kept the `textext` folder where it was downloaded (in `D:\Special Apps Setup Files\TexText-Windows-1.3.0` in my case), and then tried to follow the instructions in https://textext.github.io/textext/install/windows.html. I double-clicked on `setup_win.bat`, and it spewed the following messages:

Trying to find Inkscape...
Trying registry root HKLM [32]...
Trying registry root HKLM [64]...
Trying registry root HKCU [32]...
Inkscape considered to be installed in (value not set)
Setting executable path to (value not set)\bin
(value not set)\bin\inkscape.exe not found
Trying registry root HKCU [64]...
Inkscape considered to be installed in (value not set)
Setting executable path to (value not set)\bin
(value not set)\bin\inkscape.exe not found
Trying system path...
Inkscape neither found in the registry nor on the system path
Specifiy an explicit directory via the --inkscape-executable option
to look for if you installed Inkscape from a zip package. E.g.:
setup_win --inkscape-executable "C:\Path\to\Inkscape installation\"

Cannot continue


Press any key to continue . . .

So, after this, I opened the command prompt (as administrator), and I navigated to the location of `setup_win.bat` (`D:\Special Apps Setup Files\TexText-Windows-1.3.0\textext-1.3.0` in my case) in the command prompt, and then I ran the following command (my Inkscape's bin, doc, lib folders are in the location `D:\SpecialApps\Inkscape\` btw):

`setup_win --inkscape-executable "D:\SpecialApps\Inkscape"`

After this, the following message was shown in the command prompt:

"D:\SpecialApps\Inkscape" found
Trying to detect Python interpreter in Inkscape installation directory...
No Python interpreter found within your Inkscape installation.
Expected as "D:\SpecialApps\\python.exe"
You have to install Inkscape with the Python option enabled
in the Inkscape installer.


Press any key to continue . . .

For the part of the command `setup_win --inkscape-executable "D:\SpecialApps\Inkscape"` in double quotes, I also tried using `D:\SpecialApps\Inkscape\` (notice the backslash `\` at the end), `D:\SpecialApps\Inkscape\bin` and `D:\SpecialApps\Inkscape\bin\`. All gave similar messages saying at the end that

"You have to install Inkscape with the Python option enabled
in the Inkscape installer."

Now, I already had installed Inkscape with the Python option enabled in the Inkscape installer. But I don't know why this error message came up. Also, notice this part of the message "Expected as "D:\SpecialApps\\python.exe"" - shouldn't it have been "Expected as "D:\SpecialApps\Inkscape\bin\python.exe"", if the script indeed searched for python.exe as you mentioned?

> The script searches in the bin directory directory, as you mentioned, %INKSCAPE_DIR% is set to C:\MyApps\Inkscape\bin

And about corrupted registry values, I think that is the case with me, because the script setup could not automatically detect the Inkscape installation folder.

Anyway, after all these, I used the .exe installer, and now TexText works fine. If you need any more info, please feel free to let me know. If you need any help, I'll try to do so. The only problem is, I don't know how to script. I've used Python only for some basic scientific computation, not for developing software. But still, I'll try to do my best.

**Comment by jcwinkler** [comment]
Thanks for the detailed report. You have a non standard installation directory of Inkscape which is not stored in the Registry. Hence, you need to pass the path to the inkscape executable directly - as you did. From the message

```
[TexText][ERROR ]: Bad inkscape executable provided: D:\SpecialApps\Inkscape\bin". Abort installation.
```

I conclude that the Python interpreter has been successfully called. So, something is wrong with communication between the batch file and the Python call. I will investigate this and come back to you soon.

**Comment by SShafiP** [comment]
Ok, go ahead :-). Thank you for checking.
