### ISSUE TITLE
Prepare for Ubuntu 20.04

### ISSUE THREAD

**Issue by Esokrates** [textext/textext#179]
Just a reminder: Ubuntu 20.04 is planning to remove many python2 packages, the packages `python-gtk2` `python-gtksourceview2` are not available anymore there.

As an early adopter I can test textext there, please tell me which alternative packages should be installed there.

**Comment by sizmailov** [comment]
Thanks! We are aware of that. 

Cannot answer because there is no information on which packages will be part of 20.04 distribution. We don't even know which version of inskcape will be there. 

Of course we will update code and installation instructions for 20.04 when it become available.

**Comment by ngphuoc** [comment]
I have installed inkscape 1.0rc1 in ubuntu 20.04 with `snap install inkscape --candidate`. It would be great if textext can work for this.

**Comment by sizmailov** [comment]
snap programs run in sandboxes, currently we discourage users from using snap version of inkscape, see [doc](https://textext.github.io/textext/install/linux.html?highlight=snap#install-inkscape)

@jcwinkler We can mention snap in 1.0 too

**Comment by ngphuoc** [comment]
For some reason `~/squashfs-root/bin/inkscape &` crashed with error
```*** stack smashing detected ***: <unknown> terminated

[1]  + 21001 abort (core dumped)  ~/squashfs-root/bin/inkscape
```
Therefore I used snap. 

Anyway, I will wait for when textext supports ubuntu 20.04 then. Thanks for the awesome work!

**Comment by jcwinkler** [comment]
@ngphuoc Technical background for the **stack smashing** error: The Inkscape AppImage you extracted has been created on Ubuntu 18.04. The libraries in this appimage do not match the libraries for the gtk bindings you installed on your ubuntu 20.04 machine. Hence, this approach is not recommended on non ubuntu 18.04 systems as stated in the doc.

**Snap packages** are not supported since Inkscape does not "see" any latex environment from the sandbox it is running in.

We have to wait until official deb and rpm packages arrive in the distros...
