### ISSUE TITLE
TexText support for system-wide Python 3 installation on Windows

### ISSUE THREAD

**Issue by Gibtnix** [textext/textext#230]
Hello,

just upgraded to Inkscape 1.0 and thus tried to switch to TexText 1.0.0 as well. However, as Inkscape switched all code to Python 3, I did not install Inkscape's included Python distribution. I'm on Windows 10 and I have a system-wide Python 3 installation that is used for different stuff. I have also added it to the system path which is the closest to Linux where also the system's Python is used, at least as far as I know. Thus, I do not want to install redundant Python distributions as part of other software like Inkscape. Hence, I tried to install TexText using my system's Python 3 installation but I run into a few problems here:

- First, I tried to simply run the installation batch file. It prints an error that Python is not found, even though it is system-wide available from the Path.

- Then, I changed the python directory in the batch file accordingly. Now, everything is found except a GUI toolkit.

- Thereafter, I added the --skip-requirements-check option and the installation works, the TexText folder is copied into the Inkscape extension directly.

- Trying to use TexText prints an error: ModuleNotFoundError: No module named 'lxml'

I guess I have to install the Python dependencies using pip to fix these issues... can you tell me which ones? And might it not be a good idea to generally support system-wide Python installations that are found similarly to the other dependencies?

I would like to emphasize that I do not really know if this is an issue related to TexText or primarily to Inkscape - but still, I would like to ask here first. If this is mainly caused by currently existing incompatibilities between Inkscape and a system-wide Python installation, it's also alright for me to report an issue to the Inkscape devs.

Appreciating any comments and thanks in advance!

**Comment by jcwinkler** [comment]
The most easy way to solve this issue is to install Inkscape together with the bundled Python. You need not to worry that it corrupts your existing system wide Python installation. The Python shipped with Inkscape is included in the Inkscape installation folder and is based on msys2/mingw64. It already includes all needed libraries, for example lxml and python-lxml. Also the gtk bindings.

If you really want to use your existing Python installation you need to install all python modules needed by Inkscape and also its runtime dependencies, see https://gitlab.com/inkscape/inkscape/-/blob/master/CMakeScripts/InstallMSYS2.cmake (Currently these are "python-lxml" "python-numpy" "python-pillow" "python-six" "python-cairo" "python-gobject" + dependencies).

**Comment by Gibtnix** [comment]
Thanks for the fast response! Sure I know, that the installations do not influence each other. I just somehow dislike the redundancies to install the same thing multiple times. I also tried to install the depencies using pip, however I'm receiving installation errors with python then. Maybe additional system-wide dependencies are required as well? If so, it might indeed be better to stick with Inkcape's python installation. Thanks anyway 👍
