### ISSUE TITLE
Improve installation script (setup.py)

### ISSUE THREAD

**Issue by sizmailov** [textext/textext#28]
In release pack there is `./extension` directory while it's absent git repository. 

Right now `setup.py` copies all files from current directory to inkscape extension directory. 
It used to copy all from `./extension` folder before #14 (I "fixed" that, since I was not aware of release distribution structure). 

This should be fixed, so script would work for both dev and release distributions.

**Comment by jcwinkler** [comment]
Thanks! I exchanged the linux package for 0.8 as well.

(Reworded commit message to be precise)

Best would be to clean up this chaotic directory structure and file mixture, anyway. So that extension files are in directory `extension`, package building script in `tools`, etc. or sth. like this. But this is another discussion.
