### ISSUE TITLE
TextTxt fails to launch after succesful installation Ubuntu 20.04

### ISSUE THREAD

**Issue by diegomvd** [textext/textext#305]
I performed a TexText installation. I ran setup.py with the python3.8 of a conda installation and all required modules are found. The execution of setup.py ends with a success message. I specified hat the python interpreter to use is the python3.8 from the conda installation (changed the python interpreter in preferences.xml file). When I open Inkscape and click on Extensions -> Text -> TexText nothing happens.  Before, while I was solving other issues (missing lxml, etc...) a dialog window opened when I tried to launch TexTex displaying the error messages. 

**Summary**

All required modules found (pdflatex, gtk)
Python interpreter correctly specified in preferences.xml
After clicking on Extensions -> Text -> TexText nothing happens

**System information**

- TexText version: 1.4
- Inkscape version: 1.1
- Operating system: Ubuntu 20

**Comment by diegomvd** [comment]
Could this be related to a lack of support of Python3?

**Comment by jcwinkler** [comment]
Thanks for the report. Unfortunately, I currently have no access to my development tools. I will dive into this issue when I am back at home next weekend.
Regards, Jan

*Von: *diegomvd ***@***.***>
*An: *textext/textext ***@***.***>
*Kopie: *Subscribed ***@***.***>
*Datum: *01.08.2021 12:27:40
*Betreff: *Re: [textext/textext] TextTxt fails to launch after succesful installation (#305)

**Comment by jcwinkler** [comment]
> Before, while I was solving other issues (missing lxml, etc...)

I think that your Python installation is not correct because e.g. lxml should be installed automatically when you install Inkscape via apt-get. I suggest you set-up a clean installation of Inkscape. Then, check if the extension shipped with Inkscape work fine, e.g. `Extensions`- `Render` - `Mathematics`- `LaTeX (pdflatex)`. If this has succeeded install TextText and try again. Please post any error messages if the run of TexText fails after you performed the mentioned steps.

**Comment by diegomvd** [comment]
Thanks for your reply. I will try the clean Install tomorrow and tell you what happens
