### ISSUE TITLE
why textext windows closes after hitting save?

### ISSUE THREAD

**Issue by sbelharbi** [textext/textext#309]
hi,
just installed this extension.
1. when i hit save, the text appear in the document and the textext window closes.
not really sure why it closes unless i am missing something.
what if you want to write another text? i have to go to menu and reopen the extension or type a shortcut.
it would be better if the window stays on top in case of other usage. when the user is done, they can close it.
i use [writetex](https://inkscape.org/~longqi/%E2%98%85writetex) extension. it stays on top. when you are done, you can close it.

2. is there a way to right-click on text, and open this extension to re-edit that text?

info:
ubuntu
inkscape 1.0.2 (1.0.2+r75+1)
textext 1.4.0

thanks

**Comment by jcwinkler** [comment]
>     1. when i hit save, the text appear in the document and the textext window closes.
This is by design. Each LaTeX snippet is represented by a single svg element which is created/ edited by a single modal TexText dialog. TexText uses a custom gui, not the Inkscape extension API gui as writetex does. Reason is that the custom gui enables us to provide powerful features like multiline editing, syntax highlighting and more. Drawback is that the dialog can only be modal.

>     2. is there a way to right-click on text, and open this extension to re-edit that text
No, this is not possible. This feature is not provided by the Inkscape extension API to my knowledge.

Tip: Once you have opened TexText in an Inkscape session you can use `ALT`+ `Q` to open the TexText window again (precisely, the last used extension). Or define an own shortcut as described here: https://textext.github.io/textext/usage/faq.html#defining-keyboard-shortcut-for-opening-textext-dialog

**Comment by sbelharbi** [comment]
thanks
i see now why this behavior.
yes, i read in the doc about alt+q. but it does not fit in my workflow. i was surprise to see in the doc a definition for shortcuts, but now i understand why.
usually, i add all latex text at the end of the drawing. so, repetitive open/close is less efficient.
the major advantage of the extension is to be able to re-edit. 
re-writing full text/equation because of a typo or an update is extremely tedious. that's why i thought of using this extension an option writetex does not have.

for q2. now that i think of it, if inkscape adds every extension to right-click menu, it will be a large one.


thanks for your quick answer
closing

**Comment by jcwinkler** [comment]
@sbelharbi What I do when I need to insert a bunch of LaTeX equations at once into Inkscape (e.g. taken from a document) is the following:

1. Open TexText and insert all the LaTeX code into the TexText window
2. Hit save so the code is compiled and inserted into the svg-drawing
3. Select the generated SVG element in the drawing
4. Press `CTRL` + `SHIFT` + `G` This ungroups the equations
5. Select the parts you want to adjust in your drawing and move them to the right place.

Disadvantage of this method: You cannot re-edit the equations later because you broke the group (Workaround for that: Copy the node generated in step 1 and move the copy to an invisible layer, then you find it there if you want to re-compile something later...).

**Comment by sbelharbi** [comment]
didnt think of that.
it is a good way, but as you mentioned, there are a lot of twists nd you cant re-edit.

but, writing everything in one window could be also useful to store all the latex code at once so one doesn't have to re-write them and avoid going back and forth between inkscape and other latex-doc. then use duplicate object in inkscape over the drawn text.
then, comment all latex code in the window except the one you want to draw. still helpful if you have long latex code and you can still re-edit. latex code could become messy though...

hope this aspect will be improved in the future. it is a great extension!
thanks again
