### ISSUE TITLE
Text as text instead of raster

### ISSUE THREAD

**Issue by jgpallero** [textext/textext#374]
It would be nice if text generated by TexText were real text when the figure were exported as PDF, in order to allow select them. Is it possible?

**Comment by jcwinkler** [comment]
No, unfortunately this is not possible. During conversion from the latex generated pdf snippet into svg all text and math is converted into svg paths by the poppler library.

**Comment by nikosavola** [comment]
This feature would be very nice if possible to implement with some hack or a different library.

**Comment by jcwinkler** [comment]
Hmm, I did some research and found that it may be possible if TexText **does not** use the `--pdf-poppler` command line option when invoking Inkscape for pdf -> svg conversion. According to the doc:
![grafik](https://user-images.githubusercontent.com/11866252/203525500-67258cb8-9860-4800-a829-11b03035a576.png)
then text is kept as text. Question is what happens to the math and which font is used in Inkscape.

I will try it out.

**Comment by jcwinkler** [comment]
This is how the LaTeX-snippet

```latex
\documentclass{article}
\usepackage{amsmath,amsthm,amssymb,amsfonts}
\usepackage{color}
\pagestyle{empty}
\begin{document}
Please note: $x = \pm \sqrt{\sin(y)}$
\end{document}
```

looks like in Inkscape when the pdf is converted to svg using the `--pdf-poppler` option (as it is currently implemented in TexText):
![grafik](https://user-images.githubusercontent.com/11866252/203526842-77010b28-53e3-4f7e-8b47-652701f7c090.png)

And this how it loooks like without the `--pdf-poppler` option:
![grafik](https://user-images.githubusercontent.com/11866252/203526973-bc75b7ef-2059-4873-b53d-31c846c9694a.png)

In fact, it turns out, that the phrase "Please note" is marked as a text group, but its letters are only paths. So they cannot be edited using the text tool:

![grafik](https://user-images.githubusercontent.com/11866252/203527731-8f86b130-8648-4472-9bd3-1db6d38015dc.png)

That said I do not see an advantage by this approach. But maybe I miss something.

**Comment by jcwinkler** [comment]
Update: It is possible to ensure that text is not converted to paths:

![grafik](https://user-images.githubusercontent.com/11866252/203529076-86d638d2-f140-4142-ad82-2054f42fc017.png)

Anyway, if math is incorporated, results may become ugly. What do you think @jgpallero, @nikosavola

**Comment by jgpallero** [comment]
Of course, you are right, the results are very ugly. But Inkscape can use Latin Modern Math font. Could it be used by textext?

**Comment by nikosavola** [comment]
I wonder what the result would look like for $\LaTeX$ using the [unicode-math](https://ctan.org/pkg/unicode-math?lang=en) package. I think this requires XeTeX or LuaTeX
```latex
\usepackage{unicode-math}
\setmathfont{Latin Modern Math}
```

Not sure how the actually font embedding works in PDF -> SVG, or maybe it is needed just in Inkscape export.

**Comment by jcwinkler** [comment]
@nikosavola 

Using

```latex
\usepackage{unicode-math}
\setmathfont{Latin Modern Math}
```
we get with current version of TexText (using xelatex)

![grafik](https://user-images.githubusercontent.com/11866252/203539111-2826e103-ce10-47a0-8c93-46eb1a690225.png)

and with the option to keep text as text:

![grafik](https://user-images.githubusercontent.com/11866252/203539054-b4c8612f-0942-4018-8a21-d6ea6505edc6.png)

😞
