### ISSUE TITLE
Non-default preamle is reset when text dialog is opened

### ISSUE THREAD

**Issue by veltsov** [textext/textext#40]
When a non-default preamble is selected in the text dialog, it works for compiling and inserting into the document. It is also properly saved in the SVG file. However, when the dialog is opened again to edit the text, the preamble is reset to the default one (default_packages.tex). The reason is that clear_preamble is called during the window creation after the old preamble value is set in the constructor. The attached patch fixes the problem.
[asktext.py.patch.txt](https://github.com/textext/textext/files/2310331/asktext.py.patch.txt)

**Comment by jcwinkler** [comment]
Confirmed. Thanks @veltsov for reporting and the patch. I will test the patch and fix this.

**Comment by daviditschan** [comment]
I appear to run into the same issue using Inkscspe 1.4.4 with textext 1.12.0: when I open textext from inkscape, my preamble is reset to default_packages.tex automatically. I am using lualatex, so when I select the correct preamble I want to use, and then select pdflatex, the setting for the preamble is cleared back to default_packages.tex. Otherwise, it works fine. When I modify default_packages, these changes appear not to be saved or are not effected. Maybe an important side note: I have some issues with GTK3 so I use tkinter as a GUI toolkit. Maybe it's a bug on my system, else it would be maybe interesting to reopen this issue. At any rate I would be glad for some advice, because even though this is not a big issue, it's cumbersome when opening many textext elements in an inkscape document...

Thanks!

**Comment by jcwinkler** [comment]
OK, thanks for the report @daviditschan . I will dive into this issue and try to fix it. Please give me approx 1 week.
