### ISSUE TITLE
inkscape main window freeze

### ISSUE THREAD

**Issue by NeverGameStar** [textext/textext#407]
Current behaviour:
Whenever opening the TexText window, the main inkscape window freezes / shows no response. Only after the TexText window is closed (e.g. by saving the input), the main inkscape window responses again.
Expected behaviour:
While the TexText window is opened, the inkscape window functions as normal and the TexText window isn't closed on saving.
Issue:
It hinders work-flow that one always has to reopen the TexText window and one can't make changes in the main window while inputting text.

Steps to reproduce:
1. Install inkscape 1.3 and open a new file.
2. Install TexText from the "TexText-Windows-1.10.0.zip".
4. Open TexText window.

Screenshot:
![grafik](https://github.com/textext/textext/assets/11844851/d3b396ea-d1d1-4a4f-9e0a-18b42d0410ba)

System information:
- TexText version: 1.10.0
- Inkscape version: 1.3
- Operating system: Windows 10, 19045, 64-bit
- Windows only: LaTeX-distribution (MiKTeX, TeX-Live): MiKTeX
- Windows only: TexText installed via batch script or installer file: installed via batch script

Possible ways to fix the issue:
Implement the TexText window in a seperate thread / process.

**Comment by jcwinkler** [comment]
In contrast to most other Inkscape extension TexText uses a so-called custom GUI in order to be able to process all the meta-data that is associated with a TexText node. This is the key for offering the possibility to re-edit nodes later. The Inkscape extension API implements these type of extensions as modal (blocking) dialogs. I do not see a way to circumvent this behaviour although, as a developer of the extension, I would also highly appreciate if such a possibility exists.

If you just want to hack in a bunch of new formulas use the formula extension which is shipped by Inkscape. But keep in mind that you will not be able to re-edit the nodes later.
