### ISSUE TITLE
Use a custom latex class file in the custom preamble

### ISSUE THREAD

**Issue by jesseishi** [textext/textext#437]
**Before submitting a feature request make sure you have checked in the
  [documentation](https://textext.github.io/textext) if it does
  already exist!**
Yes, I couldn't find it.

**Is your feature request related to a problem? Please describe.**
I'm making some graphics for a scientific publication and would like the text in the graphics to be in the same style as the publication. The publication uses a custom document class, adjusting macros like `\vec` and adjusting fonts. I'd like to use these settings by importing the document class in the preamble. I first tried to add this custom document class to the same folder as my custom preamble, but I got the error ``! LaTeX Error: File someCustomClass.cls' not found``. It works when I add the custom document class to the installation of my latex compiler (MiKTeX in my case) and have MiKTeX refresh its file name database. However, this is a little error-prone as there might be new versions of this custom class coming out, and I would prefer to have a more local version of this class file next to the custom preamble rather than adding files to the MiKTeX base

**Describe the solution you'd like**
I'd like to be able to use a custom document class that I can provide in the same folder as my custom preamble.

**Additional context**
N/a.

Thanks a lot for looking into this!

**Comment by jcwinkler** [comment]
Thanks for this suggestion. This should work out of the box. Could you send me the preamble file you used for you TeX-snippets?

**Comment by jesseishi** [comment]
Thanks for your response.

My preamble is:
```
\documentclass{copernicus}
```

And the `copernicus.cls` file is in the same folder as my custom preamble. It's this file: [copernicus.txt](https://github.com/user-attachments/files/17459586/copernicus.txt) but as a `.cls` file which GitHub doesn't support (so I had to share it as a `.txt` file).

**Comment by jcwinkler** [comment]
Thanks! At this point the most reasonable explanation is the following:

- TexText reads your custom preamble from the path specified
- However, the generation of the TeX code takes place in a temporary file in a temporary directory
- Of course, the compiler will not find the class file there.

So I was wrong when I told you it should run out of the box. It will only run out of the box if the `cls` file is in the latex search path.

Solution: Add the directory in which the `cls` file resides to your latex-root. Independently of TeXText this is a wise idea, since you can hold and maintain the `cls`-file in a central place under your full control. You can easily add the directory to your MiKTeX installation via the MiKTeX settings. If you need help with that please let me know,

**Comment by jcwinkler** [comment]
Great to read this!
