### ISSUE TITLE
Scribus support

### ISSUE THREAD

**Issue by mardukbp** [textext/textext#74]
Scribus and Inkscape are probably the best known and most capable free-software tools for graphic design and desktop publishing. Among other things, Scribus supports creating PDF forms, linking (instead of embedding) images and, like Inkscape, it has a Python API. It also has the ability to render LaTeX fragments, but that is not convenient for inserting math symbols or equations, which is what TexText excels at.

My guess is that it should not require much effort to add support for Scribus. And more users will benefit from all these years of work :)

**Comment by jcwinkler** [comment]
Of course it would be great to see TexText working in further programs like Scribus. However, we need someone who is able to work on that topic and who is able to offer the support. Personally, I do use Scribus on rare circumstances and my amount of spare-time for such projects is very limited and completely used by TexText for Inkscape.

@sizmailov maybe you have plans in such directions since I found some "scribus" stuff in the `setup.py`script (L169)?

https://github.com/textext/textext/blob/16b10480e1980531d810e18382f60815798e4b86/setup.py#L163-L175

According to the API documentation of Scribus https://media.readthedocs.org/pdf/scribus-scripter/latest/scribus-scripter.pdf it should be not TOOO difficult to wrap something around the existing TexText core engine (which needs some rough polishing, too...).

**Comment by sizmailov** [comment]
@mardukbp If get it right you ask for TexText extension for Scribus, right? It would require one to replace inkscape-provided API by Scribus API inside of TexText plugin. Presumably it's not too hard, but it's a lot of work and definitely would be a separate project. Fortunately 99% of inkscape-dependent code resides in [one file](https://github.com/textext/textext/blob/develop/extension/textext/__init__.py), so two projects would not be too different. If there is one-to-one API in Scribus should not take too much efforts.

@jcwinkler I put all .py files that I found in older distributions into this list, didn't even look into it. 

I did heard about Scribus. Don't think I'll get to it in near future.

**Comment by mardukbp** [comment]
Thank you both for your prompt and detailed replies. I hope to find some time in the near future to work on this. I just finished making a math-heavy poster in Scribus and manually importing the equations from PDF files was not that optimal.

I hope you do not mind to leave this issue open in case someone else gets interested and wants to collaborate.

**Comment by jcwinkler** [comment]
@mardukbp I will keep this issue open. Some hints if you want to start on the project:

All the GUI stuff of textext is found in `asktext.py` (https://github.com/textext/textext/blob/develop/extension/textext/asktext.py). It should be independent of the program.

The connection to the Inkscape API is realized via the `TexText` class in `__init.py__` (https://github.com/textext/textext/blob/develop/extension/textext/__init__.py). This must be definitely replaced. There is some chance that the converter classes in `__init__.py` may be kept if Scribus also takes svg code. If not they have to be adapted to provide images only so you can use Scribus' `ImageAPI`.

Most important question is, of course, where to invisibly hold the LaTeX code so you can re-edit it. In Inkscape we store it in the document's svg nodes. Does Scribus offer such a possibility?

**Comment by sizmailov** [comment]
@mardukbp Hint: create a gitter chat for your project and post link to it here / invite us directly. 
It would be better to have a discussion there than here.

**Comment by mardukbp** [comment]
Scribus can import SVG files, so I guess I can reuse the code for Inkscape. 
However, the imported SVG is represented in a different format and stored
as a PAGEOBJECT node in the XML document.

The builtin LaTeX-fragment renderer inserts a PAGEOBJECT with a LATEX
child that contains the code. So I think that is definitely doable.

The stumbling block in this project is that importing vector files is not currently
exposed in the Python API. I will contact the Scribus devs and hopefully they 
will include it in the next stable release.

Therefore, the idea of setting up a Gitter chat is overkill for the time being.

**Comment by sizmailov** [comment]
@mardukbp Indeed, you can depend on inkscape and make a working zero version of the plugin for Scribus. 
Take a look at invocation of TexText from testing procedures:
https://github.com/textext/textext/blob/develop/pytests/test_compatibility.py#L195-L207
You can use this snippet with a little modification in your plugin code
Avoid passing `--text` option since it will put TexText in non-GUI mode

**Comment by mardukbp** [comment]
Thank you @sizmailov! I consulted with the Scribus devs and it turns out that the Python API already implements importing vector files. I will work on integrating Textext with Scribus and report back.
